languageCode = 'en-us'
title = 'Convert My Text'
theme = 'github.com/alex-shpak/hugo-book'
enableGitInfo = true
enableRobotsTXT = true

[module]
[[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'
